name: Free RDP
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          net user RDPUser RDPpassword /add
          net localgroup administrators RDPUser /add
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          echo "RDP Enabled"

      - name: Get Public IP
        run: |
          $ip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip" -UseBasicParsing).Content
          echo "Public IP: $ip"
