name: RDP Setup

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup RDP
      run: |
        $password = "YourPasswordHere"
        cmd.exe /c "netsh advfirewall firewall add rule name='RDP' dir=in action=allow protocol=TCP localport=3389"
        cmd.exe /c 'reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f'
        cmd.exe /c "net user runneradmin $password /add"
        cmd.exe /c 'net localgroup "Remote Desktop Users" "runneradmin" /add'
        cmd.exe /c 'net localgroup administrators "runneradmin" /add'
        Write-Output "RDP IP: $(curl -s ifconfig.me)"
        Write-Output "Username: runneradmin"
        Write-Output "Password: $password"
