name: Windows RDP Setup

on: [workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360  # الحد الأقصى المسموح به (6 ساعات)
    
    steps:
    - name: Configure RDP
      shell: powershell
      run: |
        # تعيين كلمة مرور (Arise2233)
        $password = ConvertTo-SecureString "P@ssw0rd123" -AsPlainText -Force
        
        # تمكين RDP وإعداد الجدار الناري
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # إنشاء مستخدم جديد
        New-LocalUser -Name "githubuser" -Password $password -FullName "GitHub User" -Description "Temporary RDP User"
        Add-LocalGroupMember -Group "Administrators" -Member "githubuser"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "githubuser"
        
        # الحصول على IP الخارجي
        $ip = (Invoke-WebRequest -Uri "https://api.ipify.org" -UseBasicParsing).Content
        
        # عرض معلومات الاتصال
        Write-Output "========================================"
        Write-Output "RDP Connection Details:"
        Write-Output "IP Address: $ip"
        Write-Output "Username: githubuser"
        Write-Output "Password: P@ssw0rd123"
        Write-Output "========================================"
        Write-Output "Note: This RDP will expire after 6 hours max"
